### ISSUE TITLE
Add destroy command

### ISSUE THREAD

**Issue by franta** [invidian/terraform-provider-sshcommand#17]
Please add option for command called when infrastructure is destroyed.

Eg. I am using ssh command for register gitlab runner. A also want unregister this runner when machine is destroyed (there is command for it).

**Comment by invidian** [comment]
Hm, perhaps this could be achieved using https://www.terraform.io/docs/provisioners/index.html#destroy-time-provisioners ?

**Comment by franta** [comment]
Looks promising, thanks, I will test it.
