### ISSUE TITLE
Add datasource

### ISSUE THREAD

**Issue by hongkongkiwi** [invidian/terraform-provider-sshcommand#8]
First, I want to say thank you for creating this, it's exactly what I need (!).

I would like to be able to login and just read the contents of a file as a datasource.

Is it possible to add something like this?

e.g. data "sshcommand_file" "authorized_keys" {
  host               = "example.com"
  file            = "/root/.ssh/authorized_keys"
  private_key        = "${file(".ssh/id_rsa")}"
}

**Comment by invidian** [comment]
Hey @hongkongkiwi, thanks for opening the issue.

Yes, it should definitely be possible to add something like this. The code will probably be very similar to the resource code (which means a bit of refactoring may need to be done to keep things DRY). If you like, feel free to create a PR with the implementation. I'll try adding it this week or next week too :)

**Comment by hongkongkiwi** [comment]
thank you, I appreciate your help to update when you have time.

Sorry, I'm not able to help as I'm not familiar with Golang (yet!), I'm learning it now.

**Comment by invidian** [comment]
Hey @hongkongkiwi, I released [new version](https://github.com/invidian/terraform-provider-sshcommand/releases/tag/v0.2.0) of this provider with data source implemented. It is now also available in official [Terraform Registry](https://registry.terraform.io/providers/invidian/sshcommand/latest), so if you use Terraform 0.13+, you can pull it from there :tada: 

Please give it a try and let me know if everything works as expected for you.
